### ISSUE TITLE
Puppet always execute start for program with numprocs != 1

### ISSUE THREAD

**Issue by ov7a** [ajcrowe/puppet-supervisord#103]
Status check for single process works okay. But for homogeneous group `systemctl status program` returns "No such process" because correct syntax is `systemctl status program:XX`. So, the check always fails and puppet always reapplying start command.

**Comment by ajcrowe** [comment]
Can you elaborate on this a bit more, what sholuld the XX be?

**Comment by ov7a** [comment]
XX is process name, usually contains program name and must contain process number. http://supervisord.org/configuration.html#program-x-section-settings

**Comment by xdexter** [comment]
+1
