### ISSUE TITLE
Concat fails - Could not retrieve information from environment production source

### ISSUE THREAD

**Issue by rk295** [ajcrowe/puppet-supervisord#110]
Hi,

I'm using puppet version 3.8.7 and version 0.6.1 of this module, when I use:

    include ::supervisord

To include the module, I see the following errors on a client:

```
Error: /Stage[main]/Supervisord::Config/Concat[/etc/supervisord.conf]/File[/etc/supervisord.conf]: Could not evaluate: Could not retrieve information from environment production source(s) file:/var/lib/puppet/concat/_etc_supervisord.conf/fragments.concat.out
```

I've not specified any other options, initially I just want to install the module. Is there some dependancy I don't yet have installed? Any help would be greatly appreciated!

r

**Comment by ajcrowe** [comment]
Hi @rk295 have you got the concat module in your puppet environment?

**Comment by rk295** [comment]
Yep, I certainly do. So I did a bit more poking around and couldn't get t o the bottom of it, then I ran `puppet agent -t` but without the `--noop` I use for testing and it worked fine. This was repeatable on a couple of other VMs I have for testing. Without no op, all is fine! Since its working now I've moved on. If you want to close this issue please go ahead.  However if there is anything I can do to further investigate please just shout. 

r

**Comment by naikajah** [comment]
@rk295 did you manage to resolve this error? I too am getting the same error thought not for puppet-supervisord. But the error is exactly the same

`Error: /Stage[main]/Haproxy::Config/Concat[/etc/haproxy/haproxy.cfg]/File[/etc/haproxy/haproxy.cfg]: Could not evaluate: Could not retrieve information from environment production source(s) file:/opt/puppetlabs/puppet/cache/concat/_etc_haproxy_haproxy.cfg/fragments.concat.out"`

**Comment by ajcrowe** [comment]
I believe concat needs to write fragments which are dependencies for the final file. It might be `--noop`` is not allowing these to be created hence the failure.
