### ISSUE TITLE
Configurable service name 

### ISSUE THREAD

**Issue by mvantellingen** [ajcrowe/puppet-supervisord#14]
When using package_provider = 'apt' ubuntu installs an init.d script as /etc/init.d/supervisor The service.pp file assumes that it is called /etc/init.d/supervisord. Perhaps this also needs to be configurable?

**Comment by shishirsharma** [comment]
I am getting errors with this
Execution of '/etc/init.d/supervisor start' returned 2: Starting supervisor: Error: conflicting command line option '-c'

**Comment by ajcrowe** [comment]
can you share your puppet code and operating system information @shishirsharma
