### ISSUE TITLE
Supervisor Service fails to restart on supervisord crash

### ISSUE THREAD

**Issue by panshul007** [ajcrowe/puppet-supervisord#45]
While testing the plugin, puppet starts the supervisord service and the processes managed by supervisord, but if for some reason supervisord crashes, puppet does not restart the service.
I get the following message:
    
    Notice: /Stage[main]/Main/Node[default]/Service[supervisord]/ensure: ensure changed 'stopped' to 'running'
    Info: /Stage[main]/Main/Node[default]/Service[supervisord]: Unscheduling refresh on Service[supervisord]

and the service does not come up. I am not sure if this is caused by supervisor plugin or by puppet.
Please suggest

**Comment by ajcrowe** [comment]
Can you provide the configuration you are using for the module and what OS you'r eon @panshul007

**Comment by ajcrowe** [comment]
Closing due to no response, this might be addressed in `0.6.0`
