### ISSUE TITLE
stdout_logfile & stderr_logfile misinterprets "syslog" value

### ISSUE THREAD

**Issue by znorris** [ajcrowe/puppet-supervisord#53]
Setting `stdout_logfile` or `stderr_logfile` to "syslog" results in a configuration file that reads:
```
stdout_logfile=/var/log/supervisor/syslog
stderr_logfile=/var/log/supervisor/syslog
```
This is incorrect, as it should read:
```
stdout_logfile=syslog
stderr_logfile=syslog
```
Doing so will result in the application appropriately logging to syslog instead of maintaining it's own logfile. This applies to `[program:x]`, `[fcgi-program:x]`, and `[eventlistener:x]`.

Reference:
http://supervisord.org/logging.html?highlight=syslog#child-process-logs

**Comment by znorris** [comment]
Sorry, I see that this previous issue fixed the bug: https://github.com/ajcrowe/puppet-supervisord/pull/41

Would you be willing to tag a new release?

**Comment by ajcrowe** [comment]
Should be tagging a new release in the next few days @znorris
