### ISSUE TITLE
Option to restart supervisor service on file change

### ISSUE THREAD

**Issue by tkocheran-chromeriver** [ajcrowe/puppet-supervisord#55]
The default Puppet `service` resource type allows to be notified and restarted when a configuration file is updated. Is there a way that this module could be extended so that when I change a config file for a given supervisord::program, the process if running could be restarted by supervisorctl?

**Comment by walkamongus** [comment]
I think this could be easily implemented by making the supervisord::reload class execute the `supervisorctl reload` command.

After updating an eventlistener config through the module, the old listener continued running with the old configuration despite the `supervisorctl reread` and `supervisorctl update` commands being run.

**Comment by ajcrowe** [comment]
This is strange, it was my understanding a `reread` would update the configuration but not affect the processes, and the `update` would then restart processes which had their configuration changed.

I will have to look into this.

**Comment by jonlil** [comment]
I have a case where supervisor is running a uwsgi.ini file, and if this file changes I want to restart a specific program

At the moment this is the closed I have gotten to success

```puppet

file { "/etc/config.blaha.conf":
    notify => Supervisord::Supervisorctl["restart_supervisor_program_${title}"]
}

supervisord::supervisorctl { "restart_supervisor_program_${title}":
   command => 'restart',
   process => "${title}"
}
```

But this also forces my programs to start which is not what I want, 
so if there is someway check this with onlyif?

**Comment by jonlil** [comment]
This is what I ended up with

```puppet
Exec <| title == "supervisorctl_command_restart_supervisor_program_${title}" |> {
    onlyif  => "/usr/bin/test \"`/usr/bin/supervisorctl status ${title} | grep \"RUNNING\"`\" != \"\"",
    subscribe => File["${::uwsgi::params::app_config_dir}/${hostname}.ini"],
    refreshonly => true
}

supervisord::program { $title:
    command                 => "/usr/local/bin/uwsgi --emperor ${uwsgi::params::app_config_dir}/${hostname}.ini",
    priority                => "100",
    autostart               => false,
    autorestart             => true,
    require                 => Uwsgi::App[$hostname],
}

supervisord::supervisorctl { "restart_supervisor_program_${title}":
    command => 'restart',
    process => "${title}",
}
```

Works fine for ubuntu 14.04

**Comment by joshuaspence** [comment]
Hmm, why was this issue closed?
