### ISSUE TITLE
Supervisord doesn't applies configuration right away

### ISSUE THREAD

**Issue by dene14** [ajcrowe/puppet-supervisord#63]
To reproduce, you can try to change socket file's mode and check the actual socket file permission after a puppet's pass.

I bet there is a problem appeared when module has been changed in the way it notifies supervisord after configuration changes (in init.pp):
  Class['supervisord::config'] ~> Class['supervisord::reload']

The problem is that supervisord must be restarted (not reloaded) in order to apply changes of "main" configuration (supervisord.conf). I'm not pushing PR coz I'm totally unsure the way we'd like to fix it (I use the module only 1 month long).

Locally I've added fast and dirty hack to restart supervisord on any supervisord.conf changed like that:
#####################################################################
diff --git a/supervisord/manifests/config.pp b/supervisord/manifests/config.pp
index 1c8bd8e..b6b2277 100644
--- a/supervisord/manifests/config.pp
+++ b/supervisord/manifests/config.pp
@@ -49,7 +49,8 @@ class supervisord::config inherits supervisord {
   concat { $supervisord::config_file:
     owner => 'root',
     group => '0',
\-    mode  => '0644'
\+    mode  => '0644',
\+    notify => Service["$supervisord::service_name"]
   }
 
   if $supervisord::unix_socket {
\#####################################################################

However, more sane solution would be abstract all conf file snippets related to supervisord itself in a set of concat::fragment with such a notify.

**Comment by ajcrowe** [comment]
This should have been addressed by adding the notify to the concat resource I think. https://github.com/ajcrowe/puppet-supervisord/blob/master/manifests/config.pp#L56
