### ISSUE TITLE
buffer_size validate_re gives an error with the defaults

### ISSUE THREAD

**Issue by fitzboy** [ajcrowe/puppet-supervisord#74]
when trying to run an install, I am getting:
Error: Evaluation Error: Error while evaluating a Function Call, validate_re(): 10 does not match "^\\d+" at /etc/puppetlabs/code/environments/production/modules/supervisord/manifests/eventlistener.pp:51:3

It is non-obvious why this is not matching. I am NOT setting buffer_size, leaving it as default. Any help is appreciated.

**Comment by fitzboy** [comment]
update: if I set buffer_size => '10' in the profile, then it passes the test. But if I leave it as default, it will not

**Comment by ajcrowe** [comment]
I think this is fixed by #78
