### ISSUE TITLE
ensure_process does not have any effect when set as 'running'

### ISSUE THREAD

**Issue by mathieuboniface** [ajcrowe/puppet-supervisord#75]
There is no effect when setting `ensure_process` to `running` on the `supervisord::process` even if it's not currently running.

So actually, starting a `stopped` process is not possible. 

As seen [in the code](https://github.com/ajcrowe/puppet-supervisord/blob/v0.5.2/manifests/program.pp#L111), there is no behavior described when `ensure_process` is set to `running`.

**Comment by ryaner** [comment]
We've hit this as well. I created #77 with our fix for it.

**Comment by md14454** [comment]
This is fixed by #72 which has just been merged
