### ISSUE TITLE
puppetforge latest release

### ISSUE THREAD

**Issue by aamerik** [ajcrowe/puppet-supervisord#76]
Hello, Would it be possible to submit an updated version of this module to the PuppetForge?  I'm looking for the new $program_environment param in supervisord::program and it's not in 0.5.2 (latest on forge). Thank you

**Comment by ajcrowe** [comment]
Hi @aamerik, I'll be looking to push out a 0.6 release shortly. Sorry for the delay!

**Comment by aamerik** [comment]
Thanks!!!

**Comment by aamerik** [comment]
Hi AJ!  Any chance we can have the 0.6 release on the forge?  Thank you

**Comment by ajcrowe** [comment]
It's now released
