### ISSUE TITLE
Ubuntu executable path is incorrect

### ISSUE THREAD

**Issue by calston** [ajcrowe/puppet-supervisord#82]
If a package is used instead of pip then the path is `/usr/bin/supervisord` not `/usr/local/bin/supervisord`

This can be worked around with `supervisord::executable: '/usr/bin/supervisord'` but it seems like it should know this.

**Comment by ajcrowe** [comment]
@calston this might be possible with some more logic around whether you're using pip or your system package manager. However dealing with all edge cases it tricky, generally I build the module around using `pip` as default.

If you would like to submit a PR I would be more than happy to review and add it!

**Comment by ajcrowe** [comment]
Closing, please re-open if you have a PR
