### ISSUE TITLE
Dependency issue with forge module zack/r10k

### ISSUE THREAD

**Issue by walterheck** [ajcrowe/puppet-supervisord#83]
The ajcrowe/supervisord module that is currently on the forge depends on puppetlabs-concat like this:

> puppetlabs/stdlib (>= 4.4.0 <5.0.0)
> puppetlabs/concat (>= 1.0.0 <2.0.0)

however this clashes with the current version of zack/r10k which depends on gentoo/portage:

> puppetlabs/stdlib (>= 4.6.0)
> puppetlabs/ruby (>= 0.0.2)
> puppetlabs/gcc (>= 0.0.3)
> puppetlabs/pe_gem (>= 0.0.1)
> croddy/make (>= 0.0.3)
> puppetlabs/inifile (>= 1.0.0)
> puppetlabs/vcsrepo (>= 0.1.2)
> puppetlabs/git (>= 0.0.3)
> gentoo/portage (>= 2.0.0)

the gentoo/portage module then has:

> puppetlabs/concat

and this just installs the latest version of puppetlabs/concat which is at the time of filing this issue: 

> Version 2.1.0 released Jan 26th 2016

So, in summary if there's no giant blockers in running this module with puppetlabs/concat 2.1.0 it would be awesome to have a new version pushed to the forge with updated dependencies.

**Comment by walterheck** [comment]
This isn't properly working yet: 

```
==> foss-master: ==> Configure supervisord for foreman and smart-proxy
==> foss-master: Warning: ModuleLoader: module 'supervisord' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> foss-master: Warning: ModuleLoader: module 'supervisord' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> foss-master: Warning: ModuleLoader: module 'supervisord' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> foss-master: Warning: ModuleLoader: module 'supervisord' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> foss-master: Warning: ModuleLoader: module 'supervisord' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
```

**Comment by walterheck** [comment]
@ajcrowe ping.. This is slightly annoying for us now ;)

**Comment by ajcrowe** [comment]
Sorry about this @walterheck I'll endeavour to  find some time to investigate

**Comment by walterheck** [comment]
@ajcrowe no issues. I added a PR for you, all you need to do is merge and push to the forge :)

**Comment by walterheck** [comment]
And for that I'd recommend adding puppet-blacksmith to this module: http://www.kartar.net/2014/10/using-puppet-blacksmith/
