### ISSUE TITLE
Error: curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by hasc** [ajcrowe/puppet-supervisord#94]
Hi,

I just tried to install supervisord with the default config on a fresh debian jessie as well as ubuntu 14.04 and with both OS get the same error message:

curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python returned 1 instead of one of [0]

Looks like when I execute the command with sudo privileges directly in the console everything works fine. Anyone knows if this is a bug or am I doing something wrong?

Kind regards
hasc

**Comment by rsood-trulia** [comment]
I had the same issue today(same OS etc.).  However, running with sudo privileges didn't fix it for me. I poked around a bit and I think the canonical location of the ez_setup.py script has changed recently.  I updated line 101 in the params.pp file to:

`$setuptools_url          = 'https://bootstrap.pypa.io/ez_setup.py'`

This seems to have gotten me past that issue(and supervisord is running). YMMV

**Comment by kjhenner** [comment]
I ran into the same issue and was able to resolve it by setting that setuptools_url parameter to 'https://bootstrap.pypa.io/ez_setup.py' in my declaration of the supervisord class.  If the canonical location has indeed changed, it makes sense to change the default in params.pp.

**Comment by rsood-trulia** [comment]
Submitted a PR for this change:

https://github.com/ajcrowe/puppet-supervisord/pull/95

**Comment by ajcrowe** [comment]
Fixed in #95
